# Generated by Django 3.1.5 on 2023-09-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducingCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=10, unique=True, verbose_name='Индекс страны')),
            ],
            options={
                'db_table': 'producing_countries',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.suppliers'),
        ),
        migrations.AddField(
            model_name='products',
            name='producing_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.producingcountries'),
        ),
    ]
